<?php

require_once drupal_get_path('module', 'gsb_fpp_xray') . '/gsb_fpp_xray_form_data.theme.inc';

/**
 * Implements hook_menu().
 */
function gsb_fpp_xray_menu() {
  $items = array();
  $items['admin/config/gsb'] = array(
    'title' => 'GSB',
    'description' => 'Site-specific configuration.',
    'position' => 'left',
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('access administration pages'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );  
  $items['admin/config/gsb/fpp-xray'] = array(
    'title' => 'GSB FPP Xray',
    'description' => 'Provides detailed view of an FPP',    
    'page callback' => 'drupal_get_form',
    'page arguments' => array('gsb_fpp_xray_page_form'),    
    'access arguments' => array('access administration pages'),
  );
  $items['admin/config/gsb/fpp-xray/download/%/%/%'] = array(
    'title' => 'GSB FPP Xray Download',
    'description' => 'Download the xray file',    
    'page callback' => 'gsb_fpp_xray_download',
    'page arguments' => array(5,6,7),
    'access arguments' => array('access administration pages'),
  );  
  return $items;
} 

/**
 * Menu callback; displays a Drupal page containing the GSB FPP Xray form.
 */
function gsb_fpp_xray_page_form(array $form, array &$form_state) {

  $fpid = '';
  if (isset($form_state['storage']['fpid'])) {
    $fpid = $form_state['storage']['fpid'];
  }

  $bundle = '';
  if (isset($form_state['storage']['bundle'])) {
    $bundle = $form_state['storage']['bundle'];
  }  

  $form['gsb_fpp_xray_fpid'] = array(
    '#type' => 'textfield',
    '#title' => t('FPP Id'),
    '#default_value' => $fpid,
  );

  $form['gsb_fpp_xray_bundle'] = array(
    '#type' => 'textfield',
    '#title' => t('FPP Bundle'),
    '#default_value' => $bundle,
  );  

  $form['actions'] = array('#type' => 'actions');
  $form['actions']['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Go'),
    '#submit' => array('gsb_fpp_xray_form_submit'),
  );

  $form['stuff'] = array(
    '#type' => 'markup',
    '#markup' => theme('gsb_fpp_xray_form_data', array('fpid' => $fpid, 'bundle' => $bundle)),
  );

  $form['#validate'][] = 'gsb_fpp_xray_form_validate';

  return $form;
}

/**
 * Implements hook_theme().
 *
 * Define custom theme hooks
 */
function gsb_fpp_xray_theme($existing, $type , $theme, $path) {
  return array(
    'gsb_fpp_xray_form_data' => array(
      'template' => 'gsb_fpp_xray_form_data',
      'file' => 'gsb_fpp_xray_form_data.theme.inc',
    ),
  );
}

function gsb_fpp_xray_form_validate(array &$form, array &$form_state) {

}

function gsb_fpp_xray_form_submit(array &$form, array &$form_state) {

  $fpid = $form_state['values']['gsb_fpp_xray_fpid'];
  $bundle = $form_state['values']['gsb_fpp_xray_bundle'];

  if (empty($fpid) && empty($bundle)) {
    return;
  }

  // Store values
  $form_state['storage']['fpid'] = $fpid;
  $form_state['storage']['bundle'] = $bundle;
  
  // Rebuild the form
  $form_state['rebuild'] = TRUE;   

}

function gsb_fpp_xray_download($action, $data, $file_name) {

  $info = array();

	if ($action == 'byid') {
    $fpid = $data;
    list($returned_fpp, $returned_nodes) = _gsb_fpp_xray_get_fppinfo_byid($fpid);
    $info[$fpid]['fpp'] = $returned_fpp;
    $info[$fpid]['nodes'] = $returned_nodes;
  }
  else if ($action == 'bybundle') {
    $fpps = _gsb_fpp_xray_get_fppinfo_bybundle($data);
    foreach ($fpps as $fpid) {
      list($returned_fpp, $returned_nodes) = _gsb_fpp_xray_get_fppinfo_byid($fpid);
      $info[$fpid]['fpp'] = $returned_fpp;
      $info[$fpid]['nodes'] = $returned_nodes;
    }
  }
  else {
    exit();
  }

  $file_name = str_replace('.csv', '', $file_name);
  $file_name = "temporary://" . $file_name;

  _gsb_fpp_xray_download_info($info, $file_name);

  drupal_add_http_header('Content-Type', 'application/force-download');
  drupal_add_http_header('Pragma', 'public');
  drupal_add_http_header('Cache-Control', 'max-age=0');

  @readfile($file_name);  // The @ makes it silent.
  @unlink($file_name);  // Clean up, the @ makes it silent.

  exit();

}

function _gsb_fpp_xray_dpm($input, $name = NULL, $type = 'status') {

  if (function_exists('dpm')) {
    dpm($input, $name, $type);
  } else {
    ob_start();
    print_r($input);
    $output = ob_get_clean();   
    $export = '<pre>'. $output .'</pre>'; 
    drupal_set_message($export, $type);
  }
  
}
